name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build
      working-directory: vol-3-sort-and-search/ch-5-internal-sorting/alg-c-comparison-counting/build
      run: |
        cmake ..
        make

    - name: test
      working-directory: vol-3-sort-and-search/ch-5-internal-sorting/alg-c-comparison-counting/build
      run: |
        ./comparison_count
