name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXENAME: comparison_count_tests
      BUILD_DIR: vol-3-sort-and-search/build
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: build
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cmake ..
        make

    - name: test
      working-directory: ${{env.BUILD_DIR}}
      run: ./test/$EXENAME

    - name: coverage
      working-directory: ${{env.BUILD_DIR}}
      run: |
        pip install gcovr
        gcovr -r ../ .
