name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cd vol-3-sort-and-search/ch-5-internal-sorting/alg-c-comparison-counting/build
        cmake ..
        make
    - name: run-test
      run: |
        cd vol-3-sort-and-search/ch-5-internal-sorting/alg-c-comparison-counting/build
        ./comparison_count
