name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build_and_test
      run: cd vol-3-sort-and-search/ch-5-internal-sorting/alg-c-comparison-counting; make; ./runtests.bash
