name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXENAME: comparison_count
      BUILD_DIR: vol-3-sort-and-search/ch-5-internal-sorting/alg-c-comparison-counting/build
    
    steps:
    - uses: actions/checkout@v4

    - name: build
      working-directory: ${BUILD_DIR}
      run: |
        cmake ..
        make

    - name: test
      working-directory: ${BUILD_DIR}
      run: ./$EXENAME
